# gcloud app deploy --project lostmyboots --version 1
runtime: python313

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
